apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-test-repo-subscription
  annotations:
    hub-of-hubs.open-cluster-management.io/cloning-path: /tmp
spec:
  channel: hoh-subscriptions/test-repo-git
  name: test-repo
  placement:
    local: true
    hubOfHubsGitOps: true